language: node_js
node_js:
  - "node"

after_success:
  - git config --global user.name "jaanhio"
  - git config --global user.email "jianhaot.89@gmail.com"
  - git remote rm origin
  - git remote add origin https://github.com/jaanhio/react-cicd.git
  - yarn run deploy